; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OCS Inventory Agent"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "FACTORFX"
#define MyAppURL "https://www.factorfx.com/"
#define MyAppExeName "agent-windows.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BA5D283B-3ECB-44F2-AB81-3FE690F68C99}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files\{#MyAppName}
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Djily\Desktop\LICENSE.TXT
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Djily\Desktop
OutputBaseFilename=OCS-NG
SetupIconFile=C:\Users\Djily\Documents\icone_ocs.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Djily\Documents\OCSInventory-Agent-Rework\OCSInventory-Agent-Rework\lib\setup\windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Djily\Documents\OCSInventory-Agent-Rework\OCSInventory-Agent-Rework\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon


[UninstallRun]
Filename: "{app}\lib\setup\windows\nssm.exe"; Parameters: "stop OCSInventory-Agent"; Flags: runhidden
Filename: "{app}\lib\setup\windows\nssm.exe"; Parameters: "remove OCSInventory-Agent confirm"; Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "C:\ProgramData\Agent-OCS"

[Code]
var
  Silent: Boolean;
  URL, Username, Password: String;
  LocalMode, ServiceMode: Boolean;
  InputPage: TWizardPage;
  URLLabel, UsernameLabel, PasswordLabel: TLabel;
  URLInput, UsernameInput, PasswordInput: TEdit;
  LocalCheckBox, ServiceCheckBox: TNewCheckBox;

procedure InitializeWizard;
begin
  Silent := (Pos('/SILENT', GetCmdTail) > 0) or (Pos('/VERYSILENT', GetCmdTail) > 0);
  
  // Initialize parameters from command-line if running silently
  if Silent then
  begin
    URL := ExpandConstant('{param:URL}');
    Username := ExpandConstant('{param:USERNAME}');
    Password := ExpandConstant('{param:PASSWORD}');
    LocalMode := (ExpandConstant('{param:LOCAL}') = 'True');
    ServiceMode := (ExpandConstant('{param:SERVICE}') = 'True');
  end
  else
  begin
    // If not silent, show configuration page
    InputPage := CreateCustomPage(wpLicense, 'Configuration', 'Please enter the configuration details:');
    
    URLLabel := TLabel.Create(InputPage);
    URLLabel.Parent := InputPage.Surface;
    URLLabel.Top := 30;
    URLLabel.Left := 10;
    URLLabel.Caption := 'Server URL:';
    URLInput := TEdit.Create(InputPage);
    URLInput.Parent := InputPage.Surface;
    URLInput.Top := URLLabel.Top - 3;
    URLInput.Left := URLLabel.Left + 100;
    URLInput.Width := InputPage.SurfaceWidth - 110;
    URLInput.Text := URL;

    UsernameLabel := TLabel.Create(InputPage);
    UsernameLabel.Parent := InputPage.Surface;
    UsernameLabel.Top := URLInput.Top + URLInput.Height + 15;
    UsernameLabel.Left := 10;
    UsernameLabel.Caption := 'Username:';
    UsernameInput := TEdit.Create(InputPage);
    UsernameInput.Parent := InputPage.Surface;
    UsernameInput.Top := UsernameLabel.Top - 3;
    UsernameInput.Left := UsernameLabel.Left + 100;
    UsernameInput.Width := InputPage.SurfaceWidth - 110;
    UsernameInput.Text := Username;

    PasswordLabel := TLabel.Create(InputPage);
    PasswordLabel.Parent := InputPage.Surface;
    PasswordLabel.Top := UsernameInput.Top + UsernameInput.Height + 15;
    PasswordLabel.Left := 10;
    PasswordLabel.Caption := 'Password:';
    PasswordInput := TEdit.Create(InputPage);
    PasswordInput.Parent := InputPage.Surface;
    PasswordInput.Top := PasswordLabel.Top - 3;
    PasswordInput.Left := PasswordLabel.Left + 100;
    PasswordInput.Width := InputPage.SurfaceWidth - 110;
    PasswordInput.PasswordChar := '*';
    PasswordInput.Text := Password;

    LocalCheckBox := TNewCheckBox.Create(InputPage);
    LocalCheckBox.Parent := InputPage.Surface;
    LocalCheckBox.Top := PasswordInput.Top + PasswordInput.Height + 30;
    LocalCheckBox.Left := 10;
    LocalCheckBox.Caption := 'Do not register service - agent must be launched manually';
    LocalCheckBox.Width := InputPage.SurfaceWidth - 110;
    LocalCheckBox.Checked := LocalMode;
    
    ServiceCheckBox := TNewCheckBox.Create(InputPage);
    ServiceCheckBox.Parent := InputPage.Surface;
    ServiceCheckBox.Top := LocalCheckBox.Top + LocalCheckBox.Height + 10;
    ServiceCheckBox.Left := 10;
    ServiceCheckBox.Caption := 'Register service - agent must be launched automatically';
    ServiceCheckBox.Width := InputPage.SurfaceWidth - 110;
    ServiceCheckBox.Checked := ServiceMode;
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  
  // Check if in silent mode
  if Silent then
    Exit; // Exit without performing any validation or showing messages
  
  // Perform validation only if not in silent mode
  if CurPageID = InputPage.ID then
  begin
    if URLInput.Text = '' then
    begin
      Log('Error: Please enter a valid URL.');
      Result := False;
    end
    else if UsernameInput.Text = '' then
    begin
      Log('Error: Please enter a valid Username.');
      Result := False;
    end
    else if PasswordInput.Text = '' then
    begin
      Log('Error: Please enter a valid Password.');
      Result := False;
    end;
  end;
end;

function GetURL: String;
begin
  if Silent then
    Result := URL
  else
    Result := URLInput.Text;
end;

function GetUsername: String;
begin
  if Silent then
    Result := Username
  else
    Result := UsernameInput.Text;
end;

function GetPassword: String;
begin
  if Silent then
    Result := Password
  else
    Result := PasswordInput.Text;
end;

function IsLocalMode: Boolean;
begin
  if Silent then
    Result := LocalMode
  else
    Result := LocalCheckBox.Checked;
end;

function IsServiceMode: Boolean;
begin
  if Silent then
    Result := ServiceMode
  else
    Result := ServiceCheckBox.Checked;
end;


function InstallServiceWithNSSM: Boolean;
var
  ResultCode: Integer;
  Command: String;
  NSSMPath: String;
begin
  Command := 'install OCSInventory-Agent "C:\Program Files\OCS Inventory Agent\lib\setup\windows\daemon-windows.exe"';
  NSSMPath := 'C:\Program Files\OCS Inventory Agent\lib\setup\windows\nssm.exe';
  Log('Installing service with NSSM: ' + NSSMPath + ' ' + Command);
  Result := Exec(NSSMPath, Command, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if not Result then
    MsgBox('Failed to install service with NSSM. Error code: ' + IntToStr(ResultCode), mbError, MB_OK);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  CommandAgentConfigure: String;
begin


  try
    if CurStep = ssPostInstall then
    begin
      CommandAgentConfigure := '-f true -m 0 -p ' + GetPassword() + ' -u ' + GetUsername() + ' -s ' + GetURL() + ' -d "C:\ProgramData\Agent-OCS\inventory" -l "C:\ProgramData\Agent-OCS\agent.log"';
      Log('Executing Command Agent Configuration: ' + ExpandConstant('{app}\{#MyAppExeName}') + ' ' + CommandAgentConfigure);
      
      if not Exec(ExpandConstant('{app}\{#MyAppExeName}'), CommandAgentConfigure, '', SW_HIDE, ewNoWait, ResultCode) then
      begin
        Log('Failed to configure the agent ' + ExpandConstant('{app}\{#MyAppExeName}') + ' with code ' + IntToStr(ResultCode));
      end;
      
      if IsServiceMode then
      begin
        if not InstallServiceWithNSSM then
          Log('Failed to install service.');
      end;
    end;
  except
      Log('Exception in CurStepChanged: ');
  end;
end;

