; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OCS Inventory Agent"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "OCS Inventory "
#define MyAppURL "https://www.ocsinventory.com/"
#define MyAppExeName "agent-windows.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

#define AgentPath "path_of_your_agent\OCSInventory-Agent-Rework"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{652EB54C-0A14-46AF-9F06-3BA7C294AFC9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\Program Files\{#MyAppName}
DisableDirPage=yes
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile={#AgentPath}\setup\windows\media\licence.TXT
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=Setup OCS-NG
OutputBaseFilename=OCS-NG
SetupIconFile={#AgentPath}\setup\windows\media\icone_ocs.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Files]
Source: "{#AgentPath}\setup\windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#AgentPath}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[UninstallRun]
Filename: "{app}\setup\windows\nssm.exe"; Parameters: "stop OCSInventory-Agent"; Flags: runhidden
Filename: "{app}\setup\windows\nssm.exe"; Parameters: "remove OCSInventory-Agent confirm"; Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "C:\ProgramData\Agent-OCS"

[Code]
var
  Silent: Boolean;
  URL, Username, Password, LogLevel, CertFilePath: String;
  ServiceMode, RunNow: Boolean;
  InputPage: TWizardPage;
  URLLabel, UsernameLabel, PasswordLabel, LogLevelLabel: TLabel;
  URLInput, UsernameInput, PasswordInput: TEdit;
  ServiceCheckBox, RunNowCheckBox: TNewCheckBox;
  LogLevelComboBox: TComboBox;
  CertFileLabel: TLabel;
  CertFileInput: TEdit;
  CertFileButton: TButton;

procedure BrowseCertFile(Sender: TObject);
var
  FileName: String;
begin
  if GetOpenFileName('', FileName, '', 'Certificate Files|*.crt;*.pem|All Files|*.*', 'pem') then
  begin
    CertFileInput.Text := FileName;
  end;
end;

procedure InitializeWizard;
begin
  Silent := (Pos('/SILENT', GetCmdTail) > 0) or (Pos('/VERYSILENT', GetCmdTail) > 0);
  
  // Initialize parameters from command-line if running silently
  if Silent then
  begin
    URL := ExpandConstant('{param:URL}');
    Username := ExpandConstant('{param:USERNAME}');
    Password := ExpandConstant('{param:PASSWORD}');
    ServiceMode := (ExpandConstant('{param:SERVICE}') = 'True');
    RunNow := (ExpandConstant('{param:NOW}') = 'True');
    LogLevel := ExpandConstant('{param:LOGLEVEL}');
    CertFilePath := ExpandConstant('{param:CERTIFICATE}');
  end
  else
  begin
    // If not silent, show configuration page
    InputPage := CreateCustomPage(wpLicense, 'Configuration', 'Please enter the configuration details:');
    
    URLLabel := TLabel.Create(InputPage);
    URLLabel.Parent := InputPage.Surface;
    URLLabel.Top := 30;
    URLLabel.Left := 10;
    URLLabel.Caption := 'Server URL:';
    URLInput := TEdit.Create(InputPage);
    URLInput.Parent := InputPage.Surface;
    URLInput.Top := URLLabel.Top - 3;
    URLInput.Left := URLLabel.Left + 100;
    URLInput.Width := InputPage.SurfaceWidth - 110;
    URLInput.Text := URL;

    UsernameLabel := TLabel.Create(InputPage);
    UsernameLabel.Parent := InputPage.Surface;
    UsernameLabel.Top := URLInput.Top + URLInput.Height + 15;
    UsernameLabel.Left := 10;
    UsernameLabel.Caption := 'Username:';
    UsernameInput := TEdit.Create(InputPage);
    UsernameInput.Parent := InputPage.Surface;
    UsernameInput.Top := UsernameLabel.Top - 3;
    UsernameInput.Left := UsernameLabel.Left + 100;
    UsernameInput.Width := InputPage.SurfaceWidth - 110;
    UsernameInput.Text := Username;

    PasswordLabel := TLabel.Create(InputPage);
    PasswordLabel.Parent := InputPage.Surface;
    PasswordLabel.Top := UsernameInput.Top + UsernameInput.Height + 15;
    PasswordLabel.Left := 10;
    PasswordLabel.Caption := 'Password:';
    PasswordInput := TEdit.Create(InputPage);
    PasswordInput.Parent := InputPage.Surface;
    PasswordInput.Top := PasswordLabel.Top - 3;
    PasswordInput.Left := PasswordLabel.Left + 100;
    PasswordInput.Width := InputPage.SurfaceWidth - 110;
    PasswordInput.PasswordChar := '*';
    PasswordInput.Text := Password;

    LogLevelLabel := TLabel.Create(InputPage);
    LogLevelLabel.Parent := InputPage.Surface;
    LogLevelLabel.Top := PasswordInput.Top + PasswordInput.Height + 15; // Position below PasswordInput
    LogLevelLabel.Left := 10;
    LogLevelLabel.Caption := 'Log Level:';
    LogLevelComboBox := TComboBox.Create(InputPage);
    LogLevelComboBox.Parent := InputPage.Surface;
    LogLevelComboBox.Top := LogLevelLabel.Top - 3;
    LogLevelComboBox.Left := LogLevelLabel.Left + 100;
    LogLevelComboBox.Width := InputPage.SurfaceWidth - 110;
    LogLevelComboBox.Items.Add('Error');
    LogLevelComboBox.Items.Add('Warning');
    LogLevelComboBox.Items.Add('Info');
    LogLevelComboBox.Items.Add('Verbose');
    LogLevelComboBox.ItemIndex := 2; // Default to Info

    CertFileLabel := TLabel.Create(InputPage);
    CertFileLabel.Parent := InputPage.Surface;
    CertFileLabel.Top := LogLevelComboBox.Top + LogLevelComboBox.Height + 15;
    CertFileLabel.Left := 10;
    CertFileLabel.Caption := 'Certificate File:';
    
    CertFileInput := TEdit.Create(InputPage);
    CertFileInput.Parent := InputPage.Surface;
    CertFileInput.Top := CertFileLabel.Top - 3;
    CertFileInput.Left := CertFileLabel.Left + 100;
    CertFileInput.Width := InputPage.SurfaceWidth - 200;
    
    CertFileButton := TButton.Create(InputPage);
    CertFileButton.Parent := InputPage.Surface;
    CertFileButton.Top := CertFileInput.Top;
    CertFileButton.Left := CertFileInput.Left + CertFileInput.Width + 10;
    CertFileButton.Width := 75;
    CertFileButton.Caption := 'Browse...';
    CertFileButton.OnClick := @BrowseCertFile;
    
    ServiceCheckBox := TNewCheckBox.Create(InputPage);
    ServiceCheckBox.Parent := InputPage.Surface;
    ServiceCheckBox.Top := CertFileInput.Top + CertFileInput.Height + 10;
    ServiceCheckBox.Left := 10;
    ServiceCheckBox.Caption := 'Register service - agent must be launched automatically';
    ServiceCheckBox.Width := InputPage.SurfaceWidth - 110;
    ServiceCheckBox.Checked := ServiceMode;

    RunNowCheckBox := TNewCheckBox.Create(InputPage);
    RunNowCheckBox.Parent := InputPage.Surface;
    RunNowCheckBox.Top := ServiceCheckBox.Top + ServiceCheckBox.Height + 10;
    RunNowCheckBox.Left := 10;
    RunNowCheckBox.Caption := 'Run agent now';
    RunNowCheckBox.Width := InputPage.SurfaceWidth - 110;
    RunNowCheckBox.Checked := RunNow;

  
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  
  if Silent then
    Exit;
  
  if CurPageID = InputPage.ID then
  begin
    if URLInput.Text = '' then
    begin
      Log('Error: Please enter a valid URL.');
      Result := False;
    end
    else if UsernameInput.Text = '' then
    begin
      Log('Error: Please enter a valid Username.');
      Result := False;
    end
    else if PasswordInput.Text = '' then
    begin
      Log('Error: Please enter a valid Password.');
      Result := False;
    end
    else if CertFileInput.Text = '' then
    begin
      Log('Error: Please select a certificate file.');
      Result := False;
    end;
  end;
end;

function GetURL: String;
begin
  if Silent then
    Result := URL
  else
    Result := URLInput.Text;
end;

function GetUsername: String;
begin
  if Silent then
    Result := Username
  else
    Result := UsernameInput.Text;
end;

function GetPassword: String;
begin
  if Silent then
    Result := Password
  else
    Result := PasswordInput.Text;
end;

function GetLogLevel: String;
begin
  if Silent then
    Result := LogLevel
  else
  begin
    case LogLevelComboBox.Text of
      'Error': Result := '0';
      'Warning': Result := '1';
      'Info': Result := '2';
      'Verbose': Result := '3';
      else Result := '2'; // Default to Info if something goes wrong
    end;
  end;
end;

function GetCertificateFilePath: String;
begin
  if Silent then
  begin
    Result := CertFilePath;
  end
  else
  begin
    Result := CertFileInput.Text;
  end;
end;


function IsServiceMode: Boolean;
begin
  if Silent then
    Result := ServiceMode
  else
    Result := ServiceCheckBox.Checked;
end;

function IsRunNow: Boolean;
begin
  if Silent then
    Result := RunNow
  else
    Result := RunNowCheckBox.Checked;
end;


function InstallServiceWithNSSM: Boolean;
var
  ResultCode: Integer;
  Command: String;
  NSSMPath: String;
begin
  Command := 'install OCSInventory-Agent "C:\Program Files\OCS Inventory Agent\setup\windows\daemon-windows.exe"';
  NSSMPath := 'C:\Program Files\OCS Inventory Agent\setup\windows\nssm.exe';
  Log('Installing service with NSSM: ' + NSSMPath + ' ' + Command);
  Result := Exec(NSSMPath, Command, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if not Result then
    MsgBox('Failed to install service with NSSM. Error code: ' + IntToStr(ResultCode), mbError, MB_OK);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
  CommandAgentConfigure, CommandRunNow: String;
begin

  try
    if CurStep = ssPostInstall then
    begin
      
      CommandAgentConfigure := '-f true -m 0 -p ' + GetPassword() + ' -u ' + GetUsername() + ' -s ' + GetURL() + ' -d "C:\ProgramData\Agent-OCS\inventory" -l "C:\ProgramData\Agent-OCS\agent.log"' + ' -v ' + GetLogLevel() + ' -c "' + GetCertificateFilePath()+'"';
      Log('Executing Command Agent Configuration: ' + ExpandConstant('{app}\{#MyAppExeName}') + ' ' + CommandAgentConfigure);
      Log('Cetificat path: ' + GetCertificateFilePath());
      if Exec(ExpandConstant('{app}\{#MyAppExeName}'), CommandAgentConfigure, '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
      begin
        Log('Successfully configured the agent: ' + ExpandConstant('{app}\{#MyAppExeName}'));
      end
      else
      begin
        Log('Failed to configure the agent ' + ExpandConstant('{app}\{#MyAppExeName}') + ' with code ' + IntToStr(ResultCode));
      end;

      if IsRunNow then
      begin
        CommandRunNow := '-f true -m 2 -p ' + GetPassword() + ' -u ' + GetUsername() + ' -s ' + GetURL() + ' -d "C:\ProgramData\Agent-OCS\inventory" -l "C:\ProgramData\Agent-OCS\agent.log"' + ' -v ' + GetLogLevel() + ' -c "' + GetCertificateFilePath()+'"';
        Log('Executing Command run agent: ' + ExpandConstant('{app}\{#MyAppExeName}') + ' ' + CommandRunNow);
        
        if not Exec(ExpandConstant('{app}\{#MyAppExeName}'), CommandRunNow, '', SW_HIDE, ewNoWait, ResultCode) then
        begin
          Log('Failed to run the agent ' + ExpandConstant('{app}\{#MyAppExeName}') + ' with code ' + IntToStr(ResultCode));
        end;
      end;

      if IsServiceMode then
      begin
        if not InstallServiceWithNSSM then
          Log('Failed to install service.');
      end;
    end;
  except
      Log('Exception in CurStepChanged: ');
  end;
end;
