// OCSInventory Agent
// Copyright (C) OCSInventory-NG
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import 'dart:convert';
import 'dart:io';

import 'package:intl/intl.dart';
import 'package:ocs_agent/core/common/files_utils.dart';
import 'package:ocs_agent/core/common/http_utils.dart';
import 'package:ocs_agent/core/common/json_utils.dart';
import 'package:sprintf/sprintf.dart';

import 'package:ocs_agent/core/config.dart';
import 'package:ocs_agent/core/log.dart';

import 'package:ocs_agent/core/inventory/linux/commands.dart';
import 'package:ocs_agent/core/inventory/linux/format.dart';
import 'package:ocs_agent/core/inventory/macos/commands.dart';
import 'package:ocs_agent/core/inventory/macos/format.dart';
import 'package:ocs_agent/core/inventory/windows/commands.dart';
import 'package:ocs_agent/core/inventory/windows/format.dart';

class Inventory {
  late Config config;
  late Logger logger;

  late FilesUtils filesUtils;
  late HTTPUtils httpUtils;
  late JsonUtils jsonUtils;

  late LinuxCommand linuxCommand;
  late MacOSCommand macosCommand;
  late WindowsCommand windowsCommand;
  late LinuxFormat linuxFormat;
  late MacOSFormat macosFormat;
  late WindowsFormat windowsFormat;

  late var url;
  late bool inventoryCheck;
  late int assetID;

  late String inventoryFileName;
  late File inventoryFile;
  late File inventoryBase64;

  late Map<int, String> errorCodes;

  /// Constructor.
  Inventory() {
    this.config = new Config();
    this.logger = new Logger();

    this.filesUtils = new FilesUtils();
    this.httpUtils = new HTTPUtils();
    this.jsonUtils = new JsonUtils();

    this.linuxCommand = new LinuxCommand();
    this.macosCommand = new MacOSCommand();
    this.windowsCommand = new WindowsCommand();
    this.linuxFormat = new LinuxFormat();
    this.macosFormat = new MacOSFormat();
    this.windowsFormat = new WindowsFormat();

    this.url = config.getInventoryConfig("url");
    this.inventoryCheck = false;
    this.assetID = 1;

    this.inventoryFileName = sprintf('%s/%s.json', [
      config.getInventoryConfig("data_dir"),
      DateFormat("yyyy-MM-dd_HH-mm-ss").format(DateTime.now())
    ]);
    this.inventoryFile = File(inventoryFileName);
    this.inventoryBase64 = File(sprintf(
        '%s/%s.json', [config.getInventoryConfig("data_dir"), "Base64"]));

    this.errorCodes = new Map();
  }

  /// Get the running mode of the agent.
  int getMode() {
    return int.parse(config.getInventoryConfig("mode"));
  }

  /// Check if api is working and generate token if not.
  Future<bool> checkApi() async {
    // Get data from inventory.json file
    String username = config.getInventoryConfig("username");
    String password = config.getInventoryConfig("password");
    String localToken = config.getInventoryConfig("token");

    // Try to check OCS API
    // If the status is up, return true
    // If not dislay an error message and if there is an error, return query error
    try {
      // API call
      await generateToken(username, password, localToken);
      logger.info("Checking API...");

      var response = await httpUtils.get(
          "CheckAPI", Uri.parse(url), httpUtils.getHeader(config));
      logger.verbose(response["message"]);
      if (response["status_code"] == 200) {
        logger.info("API status's up!");
        return true;
      } else {
        logger
            .verbose("(Check username or password in the configuration file)");
        logger.error("API check error!");
        return false;
      }
    } catch (exception) {
      logger.error(sprintf("HTTP query: %s", [exception.toString().trim()]));
      return false;
    }
  }

  /// Send to Api the username and password and
  /// save the token retreived in inventory.json.
  Future<bool> generateToken(
      String username, String password, String localToken) async {
    logger.info("Generating token...");
    // Try to get the token generated by the server
    // If the token is retrieved, it will be saved to inventory.json file
    // If not dislay an error message and if there is an error, return query error
    try {
      // API call
      var response = await httpUtils.post(
          "API: generateToken method",
          Uri.parse(url + "/api-auth/token"),
          {HttpHeaders.contentTypeHeader: 'application/json'},
          jsonEncode({'username': username, 'password': password}));
      logger.verbose(response["message"]);
      if (response["status_code"] == 200) {
        logger.info("Token has been retrieved from server!");
        // Get the token from the response body and compare with the local token
        // If tokens are not the same, replace the local token with the server one
        if (jsonUtils.getContentFromStringByKey(response["body"], "token") !=
            localToken) {
          config.updateInventoryConfig("token",
              jsonUtils.getContentFromStringByKey(response["body"], "token"));
          logger.info(
              "Local token has been changed with token retrieved from server!");
          return true;
        } else {
          logger.info(
              "Local token is the same as the token from server. Keep the local token.");
          return true;
        }
      } else {
        logger
            .verbose("(Check username or password in the configuration file)");
        logger.error("Failed to generate token!");
        return false;
      }
    } catch (exception) {
      logger.error(sprintf("HTTP query: %s", [exception.toString().trim()]));
      return false;
    }
  }

  /// Check if an inventory already exists on the server.
  Future<void> checkInventoryExist(Map<String, dynamic> body) async {
    String uuid = body['uuid'];
    uuid = uuid.isEmpty ? 'none' : uuid;

    logger.info(
        "Checking if there is an existing inventory of the machine on the server...");
    // Try to get an existing inventory
    // If an inventory is retrieved, return true
    // If not dislay an error message and if there is an error, return query error
    try {
      // API call
      var response = await httpUtils.get(
          "API: checkInventoryExist method",
          Uri.parse(url + "/asset/bases/?uuid=$uuid"),
          httpUtils.getHeader(config));
      logger.verbose(response["message"]);
      if (response["status_code"] == 200 && response["body"].contains(uuid)) {
        logger.info("Existing inventory found!");
        assetID = jsonDecode(response["body"])[0]["id"];
        inventoryCheck = true;
      } else {
        logger.info("No inventory found!");
        assetID = -1;
        inventoryCheck = false;
      }
    } catch (exception) {
      logger.error(sprintf("HTTP query: %s", [exception.toString().trim()]));
      inventoryCheck = false;
    }
  }

  /// Check if config file exists and save it if not
  Future<void> checkAndApplyConfig() async {
    // Get data from core.json file
    List<dynamic> confFile = config.getCoreConfigs();

    logger.info("Checking local config...");
    // If the config file is empty, we get an existing config from the API and save it locally
    if (confFile.isEmpty) {
      logger.info("local config not found ! Creating one...");
      await getConfig();
    } else {
      logger.info("Local config found!");
      await checkAndApplyConfigUpdate();
    }
  }

  /// Save the server configs in config/core.json
  Future<void> getConfig() async {
    // save the existing config locally
    List<dynamic> config = await getRemoteConfig();
    if (config.isEmpty) {
      logger.error("Can't get remote config!");
    } else {
      var encoder = new JsonEncoder.withIndent("\t");
      this.config.setCore(encoder.convert(config));
      logger.info("Remote config saved locally!");
      logger.serverLogger(assetID, 9, "Remote config saved locally!");
    }
  }

  /// Get remote config
  Future<List<dynamic>> getRemoteConfig() async {
    logger.info("Getting remote config...");
    // Try to get an existing config from the server
    // If a config is retrieved, it will be saved to core.json file
    // If not dislay an error message and if there is an error, return query error
    try {
      // API call
      var response = await httpUtils.get("API: getConfig method",
          Uri.parse(url + "/config/"), httpUtils.getHeader(config));
      logger.verbose(response["message"]);
      if (response["status_code"] == 200) {
        logger.info("Remote config found!");
        // save the existing config locally
        List<dynamic> config = json.decode(response["body"]);
        var encoder = new JsonEncoder.withIndent("\t");
        return json.decode(encoder.convert(config));
      } else {
        logger.error("Remote config not found!");
        logger.serverLogger(assetID, 10, "Remote config not found!");
        return [];
      }
    } catch (exception) {
      logger.error(sprintf("HTTP query: %s", [exception.toString().trim()]));
      return [];
    }
  }

  /// Check if the config file has been updated and save it if necessary
  Future<void> checkAndApplyConfigUpdate() async {
    // Get data from core.json file
    List<dynamic> localConfig = config.getCoreConfigs();

    // Get remote config
    List<dynamic> remoteConfig = await getRemoteConfig();

    // Compare both configs
    if (localConfig.isNotEmpty || remoteConfig.isNotEmpty) {
      logger.info(localConfig.toString());
      logger.info(remoteConfig.toString());
      if (localConfig.toString() != remoteConfig.toString()) {
        logger.info("Local config is different from remote config!");
        var encoder = new JsonEncoder.withIndent("\t");
        config.setCore(encoder.convert(remoteConfig));
        logger.info("Local config has been updated!");
        logger.serverLogger(assetID, 9, "Local config has been updated!");
      } else {
        logger.info("Local config is up to date!");
      }
    } else {
      logger.error("Can't get local or remote config!");
    }
  }

  /// Get the remote template values to create or update the local template.
  Future<bool> getRemoteTemplate(Map<String, dynamic> body) async {
    // Get templates data
    var remoteInfo = await getRemoteTemplateInfo(body);
    var localInfo = getLocalTemplateInfo();

    logger.info("Getting remote template...");
    // Check if it have both info
    if (remoteInfo["return"] != "false" || localInfo["return"] != "false") {
      var compareResult = compareTemplate(localInfo, remoteInfo);
      // Depending on result, update the template or not
      if (compareResult == 0) {
        logger.info("No need to erase current template.");
        return true;
      } else if (compareResult == 1 || compareResult == 2) {
        // Try to get the remote template
        // If templates are retrieved, save remote template locally
        // If not dislay an error message and if there is an error, return query error
        try {
          logger.info("Creating or updating the local template...");
          var id = remoteInfo["id"];
          // API call
          var response = await httpUtils.get("API: getRemoteTemplate method",
              Uri.parse(url + "/templates/$id/"), httpUtils.getHeader(config));
          logger.verbose(response["message"]);
          if (response["status_code"] == 200) {
            // Save remote template locally
            logger.info("Remote template found!");
            Map<String, dynamic> template = json.decode(response["body"]);
            var encoder = new JsonEncoder.withIndent("\t");
            config.setTemplate(encoder.convert(template));
            logger.info("Remote template has been saved locally!");
            logger.serverLogger(
                assetID, 11, "Remote template has been saved locally!");
            return true;
          } else {
            logger.error("Remote template not found!");
            logger.serverLogger(assetID, 12, "Remote template not found!");
            return false;
          }
        } catch (exception) {
          logger
              .error(sprintf("HTTP query: %s", [exception.toString().trim()]));
          return false;
        }
      } else {
        logger.error("Failed to compare result!");
        return false;
      }
    } else {
      logger.error("Can't get local or remote template info!");
      return false;
    }
  }

  /// Check if a local template exists or not.
  bool getLocalTemplate() {
    logger.info("Getting local template...");

    Map<String, dynamic> template = config.getTemplate();
    // Check if the local template exists
    if (template.isNotEmpty ||
        template.values.isNotEmpty ||
        template.keys.isNotEmpty ||
        template.length != 0) {
      logger.info("Local template found!");
      return true;
    } else {
      logger.error("Local template not found!");
      return false;
    }
  }

  /// Get the remote template id and last update.
  Future<Map<String, String>> getRemoteTemplateInfo(
      Map<String, dynamic> body) async {
    Map<String, String> info;
    String uuid = await body['uuid'];
    uuid = uuid.isEmpty ? 'none' : uuid;
    logger.info("Getting remote template info...");
    // Try to get remote template info
    // If info are retrieved, return info
    // If not dislay an error message and if there is an error, return query error
    try {
      // API call
      var responseAsset = await httpUtils.get(
          "API: getRemoteTemplateInfo method",
          Uri.parse(url + "/asset/bases/?uuid=" + uuid),
          httpUtils.getHeader(config));
      logger.verbose(responseAsset["message"]);
      if (responseAsset["status_code"] == 200 &&
          responseAsset["body"].isNotEmpty) {
        logger.info("Base inventory found!");
        // API call
        var responseTemplate = await httpUtils.get(
            "API: getRemoteTemplateInfo method",
            Uri.parse(url +
                "/templates/" +
                jsonDecode(responseAsset["body"])[0]['template'].toString() +
                "/"),
            httpUtils.getHeader(config));
        logger.verbose(responseTemplate["message"]);
        if (responseTemplate["status_code"] == 200) {
          // Create info object
          logger.info("Remote template info found!");
          info = {
            "id": jsonDecode(responseTemplate["body"])['id'].toString(),
            "last_update":
                jsonDecode(responseTemplate["body"])['last_update'].toString(),
            "return": "true",
          };
        } else if (responseTemplate["status_code"] == 404) {
          logger.error(
              "Remote template info not found! Trying to get a existing template info...");
          var os;
          if (Platform.isMacOS) {
            os = "MAC";
          } else if (Platform.isLinux) {
            os = "LIN";
          } else if (Platform.isWindows) {
            os = "WIN";
          } else {
            logger.error(
                "OS does not match any of the supported OSs! (Check Plateform class return)");
          }
          var responseGET = await httpUtils.get(
              "API: getRemoteTemplateInfo method",
              Uri.parse(url + "/templates/?os=" + os),
              httpUtils.getHeader(config));

          if (responseGET["status_code"] == 200 &&
              responseGET["body"].isNotEmpty) {
            logger.info("Remote template info filtered per OS found!");
            Map<String, dynamic> newBody = new Map();
            newBody["template"] = jsonDecode(responseGET["body"])[0]["id"];
            var responsePUT = await httpUtils.patch(
                "API: getRemoteTemplateInfo method",
                Uri.parse(url +
                    "/asset/bases/" +
                    jsonDecode(responseAsset["body"])[0]["id"].toString() +
                    "/"),
                httpUtils.getHeader(config),
                jsonEncode(newBody));
            logger.verbose(responsePUT["message"]);
            if (responsePUT["status_code"] == 200) {
              logger.info("Remote template info updated!");
              // API call
              var responseTemplate = await httpUtils.get(
                  "API: getRemoteTemplateInfo method",
                  Uri.parse(url +
                      "/templates/" +
                      newBody['template'].toString() +
                      "/"),
                  httpUtils.getHeader(config));
              logger.verbose(responseTemplate["message"]);
              if (responseTemplate["status_code"] == 200) {
                // Create info object
                logger.info("Remote template info found!");
                info = {
                  "id": jsonDecode(responseTemplate["body"])['id'].toString(),
                  "last_update":
                      jsonDecode(responseTemplate["body"])['last_update']
                          .toString(),
                  "return": "true",
                };
              } else {
                logger.error("Remote template not found!");
                info = {
                  "return": "false",
                };
              }
            } else {
              logger.error("Failed to update remote template info!");
              info = {
                "return": "false",
              };
            }
          } else {
            logger.error("Remote template info filtered per OS not found!");
            info = {
              "return": "false",
            };
          }
        } else {
          logger.error("Remote template not found!");
          info = {
            "return": "false",
          };
        }
      } else {
        logger.error("Asset base not found!");
        info = {
          "return": "false",
        };
      }
      return info;
    } catch (exception) {
      logger.error(sprintf("HTTP query: %s", [exception.toString().trim()]));
      info = {
        "return": "false",
      };
      return info;
    }
  }

  /// Get the local template id and last update.
  Map<String, String> getLocalTemplateInfo() {
    Map<String, String> info;
    if (getLocalTemplate()) {
      // Create info object
      var template = config.getTemplate();
      info = {
        "id": template["id"].toString(),
        "last_update": template["last_update"].toString(),
        "return": "true",
      };
    } else {
      info = {
        "return": "false",
      };
    }
    return info;
  }

  /// Compare both templates to know if we need to create or update the local template.
  int compareTemplate(
      Map<String, String> localInfo, Map<String, String> remoteInfo) {
    logger.info("Comparing both templates...");
    // Compare both templates info
    if (remoteInfo["id"] == localInfo["id"]) {
      logger.info("Local template exists on the server!");
      if (remoteInfo["last_update"] == localInfo["last_update"]) {
        logger.info("Local template is up to date!");
        return 0;
      } else {
        logger.info("Local template isn't up to date!");
        return 1;
      }
    } else {
      logger.info("Local template doesn't exist on the server!");
      return 2;
    }
  }

  /// Process the template and format template inventory.
  Future<Map<String, dynamic>> processTemplate() async {
    // Get the template from template.json
    var template = config.getTemplate();
    logger.info("Processing template...");
    var value = await getInventoryResult(template, template["os"]);
    var templateInventory;
    // If the value isn't empty, it creates an object with data
    // If not, return an error
    if (value.isNotEmpty) {
      templateInventory = {
        "values": value,
        "return": "true",
      };
      logger.info("Template processed successfully!");
    } else {
      templateInventory = {
        "return": "false",
      };
      logger.error("Can't process the template because it is empty!");
    }
    return templateInventory;
  }

  /// Get all informations present in the local [template]
  /// with a [os] verification and format it in json.
  Future<Map<String, dynamic>> getInventoryResult(
      Map<String, dynamic> template, String os) async {
    var format;

    // Check the os platform
    if (os == "LIN") {
      format = linuxFormat;
    } else if (template["os"] == "WIN" && Platform.isWindows) {
      format = windowsFormat;
    } else if (template["os"] == "MAC" && Platform.isMacOS) {
      format = macosFormat;
    } else {
      logger.error("OS does not match any of the supported OSs");
    }

    Map<String, dynamic> inventoryResult = new Map();

    List<dynamic> sections = template['sections'];

    for (var section in sections) {
      Map<String, dynamic> result = await getResult(os, template, section);
      var valueTarget;

      // Choose the retrieval format
      switch (section['retrival_output']) {
        case "TBLE":
          valueTarget = format.getByArray(section["fields"], result);
          break;
        case "JSON":
          valueTarget = format.getByJson(section["fields"], result);
          break;
        case "PTXT":
          valueTarget = await format.getByPtxt(section["fields"], result);
          break;
        case "REGX":
          valueTarget = format.getByRegx(section["fields"], result);
          break;
        case "GREP":
          valueTarget = format.getByGrep(section["fields"], result);
          break;
        default:
          valueTarget = null;
          break;
      }
      inventoryResult.putIfAbsent(section['name'], () => valueTarget);
    }

    return inventoryResult;
  }

  /// Get the result
  Future<Map<String, dynamic>> getResult(String os,
      Map<String, dynamic> template, Map<String, dynamic> section) async {
    late var command;
    Map<String, dynamic> result = new Map();

    // Check the os platform
    if (os == "LIN") {
      command = this.linuxCommand;
    } else if (template["os"] == "WIN" && Platform.isWindows) {
      command = this.windowsCommand;
    } else if (template["os"] == "MAC" && Platform.isMacOS) {
      command = this.macosCommand;
    } else {
      logger.error("OS does not match any of the supported OSs");
    }

    Map<String, dynamic> main = new Map<String, dynamic>();
    Map<String, dynamic> options = new Map<String, dynamic>();
    if (section['options'] != null) {
      options = section['options'];
    }

    String mainRes =
        await command.getResult(section["target"], section['retrival_method']);
    main.putIfAbsent('name', () => section['name']);
    main.putIfAbsent('type', () => section['retrival_output']);
    main.putIfAbsent('options', () => options);
    main.putIfAbsent('result', () => mainRes);
    result.putIfAbsent('main', () => main);
    List<dynamic> test = section['fields'];
    var fieldOver = test.where((element) => element["override_target"]);

    for (var field in fieldOver) {
      Map<String, dynamic> sub = new Map<String, dynamic>();
      String res = await command.getResult(
          field["new_target"], field['retrival_method']);
      sub.putIfAbsent('name', () => field['name']);
      sub.putIfAbsent('type', () => field['retrival_output']);
      sub.putIfAbsent('options', () => field['options']);
      sub.putIfAbsent('result', () => res);
      result.putIfAbsent(field['name'], () => sub);
    }

    return result;
  }

  /// Create or update the inventory and send it to the server.
  Future<void> sendRemoteBaseInventory(Map<String, dynamic> body) async {
    if (inventoryCheck) {
      String uuid = await body['uuid'];
      uuid = uuid.isEmpty ? 'none' : uuid;

      logger.info("Sending base inventory to server...");
      // Try to get the existing inventory
      // If an inventory is retrieved, check its uuid
      // If an uuid exists, update the current inventory or create one if not
      // If not dislay an error message and if there is an error, return query error
      try {
        // API call
        var response = await httpUtils.get(
            "API: sendRemoteBaseInventory method",
            Uri.parse(url + "/asset/bases/?uuid=$uuid"),
            httpUtils.getHeader(config));
        logger.verbose(response["message"]);

        if (response["status_code"] == 200) {
          // Check if the uuid exists
          if (response["body"].contains(uuid)) {
            // Update the inventory
            logger.info("Updating inventory...");
            var id = jsonDecode(response["body"])[0]['id'];
            // API call
            var responsePut = await httpUtils.put(
                "API: sendRemoteBaseInventory method",
                Uri.parse(url + "/asset/bases/$id/"),
                httpUtils.getHeader(config),
                jsonEncode(body));
            logger.verbose(responsePut["message"]);

            if (responsePut["status_code"] == 200) {
              logger.info("Base inventory update has been sent to the server!");
              logger.serverLogger(
                  assetID, 2, "Inventory updated successfully!");
            } else {
              logger.error("Failed to send inventory update!");
              logger.serverLogger(
                  assetID, 5, "Failed to send inventory update!");
            }
          } else {
            logger.error("Can't get the UUID from the base inventory!");
            logger.serverLogger(
                assetID, 5, "Can't get the UUID from the base inventory!");
          }
        } else {
          logger.error("Can't get inventory from server!");
          logger.serverLogger(assetID, 5, "Can't get inventory from server!");
        }
      } catch (exception) {
        logger.error(sprintf("HTTP query: %s", [exception.toString().trim()]));
        logger.serverLogger(assetID, 5,
            sprintf("HTTP query: %s", [exception.toString().trim()]));
      }
    } else {
      // Create the inventory
      logger.info("Creating new inventory...");
      // API call
      var responsePost = await httpUtils.post(
          "API: sendRemoteBaseInventory method",
          Uri.parse(url + "/asset/bases/"),
          httpUtils.getHeader(config),
          jsonEncode(body));
      logger.verbose(responsePost["message"]);
      if (responsePost["status_code"] == 200) {
        logger.info("New inventory has been sent to the server!");
        logger.serverLogger(assetID, 1, "Inventory created successfully!");
      } else {
        logger.error("Failed to send new inventory!");
        logger.serverLogger(assetID, 5, "Failed to send new inventory!");
      }
    }
  }

  /// Update the remote inventory to add template inventory
  Future<void> sendRemoteTemplateInventory(Map<String, dynamic> body) async {
    if (await getRemoteTemplate(body)) {
      var templateInventory = await processTemplate();
      logger.info("Sending template inventory to server...");
      if (templateInventory["return"] != false) {
        logger.info("Getting remote base inventory...");
        String uuid = await body['uuid'];
        uuid = uuid.isEmpty ? 'none' : uuid;
        try {
          // API call
          var response = await httpUtils.get(
              "API: sendRemoteTemplateInventory method",
              Uri.parse(url + "/asset/bases/?uuid=$uuid"),
              httpUtils.getHeader(config));
          logger.verbose(response["message"]);
          if (response["status_code"] == 200) {
            logger.info("Remote base inventory found!");
            // If there is a uuid in the inventory, update the current inventory
            // Else, return an error
            if (response["body"].contains(uuid)) {
              logger.info("Updating base inventory...");
              var content = jsonDecode(response["body"])[0];
              var encoder = new JsonEncoder.withIndent("\t");
              content["template_inventory"] = templateInventory["values"];
              late var sectionBase64, sectionBytes, sectionJson;
              var updatedInventory = new Map();
              sectionJson = new Map();
              content["template_inventory"].keys.forEach((element) {
                sectionBytes = utf8
                    .encode(content["template_inventory"][element].toString());
                sectionBase64 = base64.encode(sectionBytes);
                sectionJson[element] = sectionBase64;
              });
              if (!inventoryBase64.existsSync()) {
                logger.error("Can't find base64 file, creating one...");
                inventoryBase64.createSync(recursive: true);
                filesUtils.writeFile(inventoryBase64, "{}");
              }
              logger.info("Base64 file found!");
              var fileBase64 = jsonDecode(inventoryBase64.readAsStringSync());
              sectionJson.keys.forEach((newKey) {
                fileBase64.keys.forEach((oldKey) {
                  if (newKey == oldKey) {
                    if (sectionJson[newKey] == fileBase64[oldKey]) {
                      logger.verbose(sprintf(
                          "%s section hasn't changed since last inventory.",
                          [newKey.toString()]));
                    } else {
                      logger.verbose(sprintf(
                          "%s section will be sent and updated.",
                          [newKey.toString()]));
                      updatedInventory[newKey] =
                          content["template_inventory"][newKey];
                    }
                  }
                });
                if (!fileBase64.containsKey(newKey)) {
                  logger.verbose(sprintf("%s section added to the inventory.",
                      [newKey.toString()]));
                  updatedInventory[newKey] =
                      content["template_inventory"][newKey];
                }
              });
              filesUtils.writeFile(
                  inventoryBase64, encoder.convert(sectionJson));
              var inventoryExist = await httpUtils.get(
                  "API: sendRemoteTemplateInventory method",
                  Uri.parse(url + "/asset/sections/?base=$assetID"),
                  httpUtils.getHeader(config));
              if (inventoryExist["status_code"] == 200) {
                content["template_inventory"] = updatedInventory;
                var responsePatch = await httpUtils.patch(
                    "API: sendRemoteTemplateInventory method",
                    Uri.parse("$url/asset/collection/"),
                    httpUtils.getHeader(config),
                    encoder.convert(content));
                logger.verbose(responsePatch["message"]);
                if (responsePatch["status_code"] == 200) {
                  logger.info(
                      "Template inventory updated to remote base inventory!");
                  logger.serverLogger(assetID, 4,
                      "Template inventory updated to remote base inventory!");
                } else {
                  logger.error(
                      "Can't update template inventory to remote base inventory!");
                  logger.serverLogger(assetID, 6,
                      "Can't update template inventory to remote base inventory!");
                }
              } else {
                // API call
                var responsePut = await httpUtils.put(
                    "API: sendRemoteTemplateInventory method",
                    Uri.parse(url + "/asset/collection/"),
                    httpUtils.getHeader(config),
                    encoder.convert(content));
                logger.verbose(responsePut["message"]);
                if (responsePut["status_code"] == 200) {
                  logger.info(
                      "Template inventory added to remote base inventory!");
                  logger.serverLogger(
                      assetID, 6, "Missing UUID in base inventory!");
                } else {
                  logger.error(
                      "Can't upload template inventory to remote base inventory!");
                }
              }
            } else {
              logger.error("Missing UUID in base inventory!");
              logger.serverLogger(
                  assetID, 6, "Missing UUID in base inventory!");
            }
          } else {
            logger.error("Can't get base inventory from server!");
            logger.serverLogger(
                assetID, 6, "Can't get base inventory from server!");
          }
        } catch (exception) {
          logger
              .error(sprintf("HTTP query: %s", [exception.toString().trim()]));
        }
      } else {
        logger.error("Failed to process template!");
      }
    } else {
      logger.error("Can't get remote template!");
    }
  }

  /// Create a local inventory in the JSON format.
  void sendLocalBaseInventory(Map<String, dynamic> body) {
    logger.info("Creating base inventory file...");
    logger.info("Writing base inventory locally...");
    // Create a file to save the new inventory
    inventoryFile.create(recursive: true);
    var encoder = JsonEncoder.withIndent("\t");
    // Write the new inventory inside
    filesUtils.writeFile(inventoryFile, encoder.convert(body));
    logger
        .info(sprintf("New base inventory created in %s", [inventoryFileName]));
  }

  /// Update the local inventory to add template inventory
  Future<void> sendLocalTemplateInventory() async {
    logger.info("Adding template inventory locally...");

    if (getLocalTemplate()) {
      var templateInventory = await processTemplate();

      if (templateInventory["return"] != false) {
        // Get the local inventory
        var content = jsonDecode(inventoryFile.readAsStringSync());
        var encoder = new JsonEncoder.withIndent("\t");
        content["template_inventory"] = templateInventory["values"];
        logger.verbose(content["template_inventory"].toString());
        // Write into inventory file
        filesUtils.writeFile(inventoryFile, encoder.convert(content));
        logger.info("Template inventory added to base inventory!");
      } else {
        logger.error("Failed to process template!");
      }
    } else {
      logger.error("Can't get local template!");
    }
  }
}
