// OCSInventory Agent
// Copyright (C) OCSInventory-NG
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// External package imports
import 'dart:convert';
import 'dart:io';
import 'package:intl/intl.dart';
import 'package:sprintf/sprintf.dart';

// Core imports
import 'package:ocs_agent/core/log.dart';
import 'package:ocs_agent/core/config.dart';

import 'package:ocs_agent/core/inventory/linux/commands.dart';
import 'package:ocs_agent/core/inventory/linux/format.dart';

import 'package:ocs_agent/core/inventory/macos/commands.dart';
import 'package:ocs_agent/core/inventory/macos/format.dart';

import 'package:ocs_agent/core/inventory/windows/commands.dart';
import 'package:ocs_agent/core/inventory/windows/format.dart';

// Common imports
import 'package:ocs_agent/core/common/files_utils.dart';
import 'package:ocs_agent/core/common/http_utils.dart';
import 'package:ocs_agent/core/common/json_utils.dart';

class Inventory {
  late Logger logger;
  late Config config;
  late FilesUtils filesUtils;
  late HTTPUtils httpUtils;
  late JsonUtils jsonUtils;
  late LinuxCommand linuxCommand;
  late LinuxFormat linuxFormat;
  late MacOSCommand macOSCommand;
  late MacOSFormat macOSFormat;
  late WindowsCommand windowsCommand;
  late WindowsFormat windowsFormat;

  late var url;
  late bool inventoryCheck;
  late int assetID;

  late String inventoryFileName;
  late File inventoryFile;
  late File inventoryBase64;

  late Map<int, String> errorCodes;

  /// Constructor.
  Inventory(
    Logger logger,
    Config config,
    FilesUtils filesUtils,
    HTTPUtils httpUtils,
    JsonUtils jsonUtils,
    LinuxCommand linuxCommand,
    LinuxFormat linuxFormat,
    MacOSCommand macOSCommand,
    MacOSFormat macOSFormat,
    WindowsCommand windowsCommand,
    WindowsFormat windowsFormat,
  ) {
    this.logger = logger;
    this.config = config;
    this.filesUtils = filesUtils;
    this.httpUtils = httpUtils;
    this.jsonUtils = jsonUtils;
    this.linuxCommand = linuxCommand;
    this.linuxFormat = linuxFormat;
    this.macOSCommand = macOSCommand;
    this.macOSFormat = macOSFormat;
    this.windowsCommand = windowsCommand;
    this.windowsFormat = windowsFormat;

    this.url = config.getInventoryConfig("url");
    this.inventoryCheck = false;
    this.assetID = 0;

    this.inventoryFileName = sprintf('%s/%s.json', [
      config.getInventoryConfig("data_directory"),
      DateFormat("yyyy-MM-dd_HH-mm-ss").format(DateTime.now())
    ]);
    this.inventoryFile = File(inventoryFileName);
    this.inventoryBase64 = File(sprintf(
        '%s/%s.json', [config.getInventoryConfig("data_directory"), "Base64"]));

    this.errorCodes = new Map();
  }

  /// Get the running mode of the agent.
  int getMode() {
    return config.getInventoryConfig("mode");
  }

  /// Check if api is working and generate token if not.
  Future<bool> checkApi() async {
    // Get data from inventory.json file
    String username = config.getInventoryConfig("username");
    String password = config.getInventoryConfig("password");
    String localToken = config.getInventoryConfig("token");

    // Try to check OCS API
    // If the status is up, return true
    // If not dislay an error message and if there is an error, return query error

    // API call
    await generateToken(username, password, localToken);
    logger.info(this.runtimeType.toString(), "Checking API availability...");

    var response =
        await httpUtils.get(Uri.parse(url), httpUtils.getHeader(config));

    if (response["status_code"] == 200) {
      logger.verbose(this.runtimeType.toString(), response["message"]);
      logger.info(this.runtimeType.toString(), "API is online!");
      return true;
    } else {
      logger.verbose(this.runtimeType.toString(),
          "Check username or password in the configuration file.");
      logger.error(this.runtimeType.toString(), "API connection failed!");
      return false;
    }
  }

  /// Send to Api the username and password and
  /// save the token retreived in inventory.json.
  Future<bool> generateToken(
      String username, String password, String localToken) async {
    try {
      logger.info(this.runtimeType.toString(), "Generating token...");
      // Try to get the token generated by the server
      // If the token is retrieved, it will be saved to inventory.json file
      // If not dislay an error message and if there is an error, return query error

      // API call
      var response = await httpUtils.post(
          Uri.parse(url + "/api-auth/token"),
          {HttpHeaders.contentTypeHeader: 'application/json'},
          jsonEncode({'username': username, 'password': password}));

      if (response["status_code"] == 200) {
        logger.verbose(this.runtimeType.toString(), response["message"]);
        logger.info(
            this.runtimeType.toString(), "Token retrieved successfully.");
        // Get the token from the response body and compare with the local token
        // If tokens are not the same, replace the local token with the server one
        if (jsonUtils.getContentFromStringByKey(response["body"], "token") !=
            localToken) {
          config.updateInventoryConfig("token",
              jsonUtils.getContentFromStringByKey(response["body"], "token"));
          logger.info(this.runtimeType.toString(),
              "Local token updated with server token.");
          return true;
        } else {
          logger.info(this.runtimeType.toString(),
              "Local token matches server token. No update required.");
          return true;
        }
      } else {
        logger.verbose(this.runtimeType.toString(),
            "Check username or password in the configuration file.");
        logger.error(this.runtimeType.toString(), "Token generation failed!");
        return false;
      }
    } catch (e) {
      logger.error(
          this.runtimeType.toString(), "Exception during token generation: $e");
      return false;
    }
  }

  /// Verify if an inventory already exists on the server.
  Future<void> checkInventoryExist(Map<String, dynamic> body) async {
    String uuid = body['uuid'];
    uuid = uuid.isEmpty ? 'none' : uuid;

    logger.info(this.runtimeType.toString(),
        "Checking if device inventory already exists...");
    // Try to get an existing inventory
    // If an inventory is retrieved, return true
    // If not dislay an error message and if there is an error, return query error

    // API call
    var response = await httpUtils.get(
        Uri.parse(url + "/asset/bases/?uuid=$uuid"),
        httpUtils.getHeader(config));
    logger.verbose(this.runtimeType.toString(), response["message"]);
    if (response["status_code"] == 200 && response["body"].contains(uuid)) {
      logger.info(this.runtimeType.toString(), "Existing inventory found!");
      assetID = jsonDecode(response["body"])[0]["id"];
      inventoryCheck = true;
    } else {
      logger.info(this.runtimeType.toString(), "No existing inventory found.");
      assetID = -1;
      inventoryCheck = false;
    }
  }

  /// Check if config file exists and save it if not
  Future<void> checkAndApplyConfig() async {
    logger.info(this.runtimeType.toString(), "Loading local configuration...");
    // Get data from core.json file
    List<dynamic> localConfig = config.getCoreConfigs();

    logger.info(
        this.runtimeType.toString(), "Verifying local configuration...");
    // If the config file is empty, we get an existing config from the API and save it locally
    if (localConfig.isEmpty) {
      logger.info(this.runtimeType.toString(),
          "Local configuration not found! Creating a new one...");
      await getConfig();
    } else {
      logger.info(this.runtimeType.toString(), "Local configuration found.");
      await checkAndApplyConfigUpdate();
    }
  }

  /// Save the server configs in config/core.json
  Future<void> getConfig() async {
    // save the existing config locally
    List<dynamic> config = await getRemoteConfig();
    if (config.isEmpty) {
      logger.error(this.runtimeType.toString(),
          "Unable to retrieve remote configuration.");
    } else {
      var encoder = new JsonEncoder.withIndent("\t");
      this.config.setCore(encoder.convert(config));
      logger.info(
          this.runtimeType.toString(), "Remote configuration saved locally.");
      logger.serverLogger(assetID, 9, "Remote configuration saved locally.");
    }
  }

  /// Get remote config
  Future<List<dynamic>> getRemoteConfig() async {
    logger.info(
        this.runtimeType.toString(), "Retrieving remote configuration...");
    // Try to get an existing config from the server
    // If a config is retrieved, it will be saved to core.json file
    // If not dislay an error message and if there is an error, return query error

    // API call
    var response = await httpUtils.get(
        Uri.parse(url + "/asset/configs/"), httpUtils.getHeader(config));
    logger.verbose(this.runtimeType.toString(), response["message"]);
    if (response["status_code"] == 200) {
      logger.info(this.runtimeType.toString(), "Remote configuration found.");
      // save the existing config locally
      List<dynamic> config = json.decode(response["body"]);
      var encoder = new JsonEncoder.withIndent("\t");
      return json.decode(encoder.convert(config));
    } else {
      logger.error(
          this.runtimeType.toString(), "Remote configuration not found.");
      logger.serverLogger(assetID, 10, "Remote configuration not found.");
      return [];
    }
  }

  /// Check if the config file has been updated and save it if necessary
  Future<void> checkAndApplyConfigUpdate() async {
    // Get data from core.json file
    List<dynamic> localConfig = config.getCoreConfigs();

    // Get remote config
    List<dynamic> remoteConfig = await getRemoteConfig();

    // Compare both configs
    if (localConfig.isNotEmpty || remoteConfig.isNotEmpty) {
      logger.verbose(this.runtimeType.toString(), localConfig.toString());
      logger.verbose(this.runtimeType.toString(), remoteConfig.toString());
      if (localConfig.toString() != remoteConfig.toString()) {
        logger.info(this.runtimeType.toString(),
            "Local configuration differs from the remote configuration. Updating...");
        var encoder = new JsonEncoder.withIndent("\t");
        config.setCore(encoder.convert(remoteConfig));
        logger.info(
            this.runtimeType.toString(), "Local configuration updated.");
        logger.serverLogger(assetID, 9, "Local configuration updated.");
      } else {
        logger.info(
            this.runtimeType.toString(), "Local configuration is up-to-date.");
      }
    } else {
      logger.error(this.runtimeType.toString(),
          "Unable to retrieve local or remote configuration.");
    }
  }

  /// Get the remote template values to create or update the local template.
  Future<bool> getRemoteTemplate(Map<String, dynamic> body) async {
    // Get templates data
    var remoteInfo = await getRemoteTemplateInfo(body);
    var localInfo = getLocalTemplateInfo();

    if (remoteInfo["return"] != "false" || localInfo["return"] != "false") {
      var compareResult = compareTemplate(localInfo, remoteInfo);
      // Depending on result, update the template or not
      if (compareResult == 0) {
        logger.info(
            this.runtimeType.toString(), "Current template is up-to-date.");
        return true;
      } else if (compareResult == 1 || compareResult == 2) {
        // Try to get the remote template
        // If templates are retrieved, save remote template locally
        // If not dislay an error message and if there is an error, return query error

        logger.info(this.runtimeType.toString(),
            "Creating or updating local template with the remote version...");

        var id = remoteInfo["id"];
        var response = await httpUtils.get(
            Uri.parse(url + "/templates/$id/"), httpUtils.getHeader(config));
        logger.verbose(this.runtimeType.toString(), response["message"]);
        if (response["status_code"] == 200) {
          // Save remote template locally
          logger.info(this.runtimeType.toString(), "Remote template found.");
          Map<String, dynamic> template = json.decode(response["body"]);
          var encoder = new JsonEncoder.withIndent("\t");
          config.setTemplate(encoder.convert(template));
          logger.info(
              this.runtimeType.toString(), "Remote template saved locally.");
          logger.serverLogger(assetID, 11, "Remote template saved locally.");
          return true;
        } else {
          logger.error(
              this.runtimeType.toString(), "Remote template not found.");
          logger.serverLogger(assetID, 12, "Remote template not found.");
          return false;
        }
      } else {
        logger.error(
            this.runtimeType.toString(), "Template comparison failed.");
        return false;
      }
    } else {
      logger.error(this.runtimeType.toString(),
          "Unable to retrieve local or remote template.");
      return false;
    }
  }

  /// Check if a local template exists.
  bool getLocalTemplate() {
    logger.info(this.runtimeType.toString(), "Loading local template...");

    Map<String, dynamic> template = config.getTemplate();
    // Check if the local template exists
    if (template.isNotEmpty ||
        template.values.isNotEmpty ||
        template.keys.isNotEmpty ||
        template.length != 0) {
      logger.info(this.runtimeType.toString(), "Local template found.");
      return true;
    } else {
      logger.error(this.runtimeType.toString(), "Local template not found");
      return false;
    }
  }

  /// Get the remote template id and last update.
  Future<Map<String, String>> getRemoteTemplateInfo(
      Map<String, dynamic> body) async {
    String uuid = await body['uuid'];
    uuid = uuid.isEmpty ? 'none' : uuid;
    logger.info(this.runtimeType.toString(),
        "Retrieving remote template information...");
    // Try to get remote template info
    // If info are retrieved, return info
    // If not dislay an error message and if there is an error, return query error

    // API call
    var responseAsset = await httpUtils.get(
        Uri.parse(url + "/asset/bases/?uuid=" + uuid),
        httpUtils.getHeader(config));
    logger.verbose(this.runtimeType.toString(), responseAsset["message"]);
    if (responseAsset["status_code"] == 200 &&
        jsonDecode(responseAsset["body"]).isNotEmpty) {
      logger.info(this.runtimeType.toString(), "Base inventory found.");
      // API call
      var responseTemplate = await httpUtils.get(
          Uri.parse(url +
              "/templates/" +
              jsonDecode(responseAsset["body"])[0]['template'].toString() +
              "/"),
          httpUtils.getHeader(config));
      logger.verbose(this.runtimeType.toString(), responseTemplate["message"]);
      if (responseTemplate["status_code"] == 200) {
        // Create info object
        logger.info(this.runtimeType.toString(), "Remote template found.");
        return {
          "id": jsonDecode(responseTemplate["body"])['id'].toString(),
          "last_update":
              jsonDecode(responseTemplate["body"])['last_update'].toString(),
          "return": "true",
        };
      } else if (responseTemplate["status_code"] == 404) {
        logger.error(this.runtimeType.toString(),
            "No remote template found. Trying to find a template matching the operating system.");
        var os;
        if (Platform.isMacOS) {
          os = "MAC";
        } else if (Platform.isLinux) {
          os = "LIN";
        } else if (Platform.isWindows) {
          os = "WIN";
        } else {
          logger.error(this.runtimeType.toString(),
              "Unsupported OS detected. Failed to find a matching template.");
        }
        var responseGET = await httpUtils.get(
            Uri.parse(url + "/templates/?os=" + os),
            httpUtils.getHeader(config));

        if (responseGET["status_code"] == 200 &&
            jsonDecode(responseGET["body"]).isNotEmpty) {
          logger.info(this.runtimeType.toString(),
              "Found a template matching the operating system.");
          Map<String, dynamic> newBody = new Map();
          newBody["template"] = jsonDecode(responseGET["body"])[0]["id"];
          var responsePUT = await httpUtils.patch(
              Uri.parse(url +
                  "/asset/bases/" +
                  jsonDecode(responseAsset["body"])[0]["id"].toString() +
                  "/"),
              httpUtils.getHeader(config),
              jsonEncode(newBody));
          logger.verbose(this.runtimeType.toString(), responsePUT["message"]);
          if (responsePUT["status_code"] == 200) {
            logger.info(this.runtimeType.toString(),
                "Successfully updated remote template.");
            // API call
            var responseTemplate = await httpUtils.get(
                Uri.parse(
                    url + "/templates/" + newBody['template'].toString() + "/"),
                httpUtils.getHeader(config));
            logger.verbose(
                this.runtimeType.toString(), responseTemplate["message"]);
            if (responseTemplate["status_code"] == 200) {
              // Create info object
              logger.info(
                  this.runtimeType.toString(), "Remote template found.");
              return {
                "id": jsonDecode(responseTemplate["body"])['id'].toString(),
                "last_update":
                    jsonDecode(responseTemplate["body"])['last_update']
                        .toString(),
                "return": "true",
              };
            } else {
              logger.error(
                  this.runtimeType.toString(), "Remote template not found.");
              return {
                "return": "false",
              };
            }
          } else {
            logger.error(this.runtimeType.toString(),
                "Failed to update remote template.");
            return {
              "return": "false",
            };
          }
        } else {
          logger.error(this.runtimeType.toString(),
              "Unable to find remote template for this OS.");
          return {
            "return": "false",
          };
        }
      } else {
        logger.error(this.runtimeType.toString(), "Remote template not found.");
        return {
          "return": "false",
        };
      }
    } else {
      logger.error(this.runtimeType.toString(), "Asset base not found.");
      return {
        "return": "false",
      };
    }
  }

  /// Get the local template id and last update.
  Map<String, String> getLocalTemplateInfo() {
    Map<String, String> info;
    if (getLocalTemplate()) {
      // Create info object
      var template = config.getTemplate();
      info = {
        "id": template["id"].toString(),
        "last_update": template["last_update"].toString(),
        "return": "true",
      };
    } else {
      info = {
        "return": "false",
      };
    }
    return info;
  }

  /// Compare both templates to know if we need to create or update the local template.
  int compareTemplate(
      Map<String, String> localInfo, Map<String, String> remoteInfo) {
    logger.info(this.runtimeType.toString(), "Comparing templates...");
    // Compare both templates info
    if (remoteInfo["id"] == localInfo["id"]) {
      logger.info(
          this.runtimeType.toString(), "Local template exists on the server.");
      if (remoteInfo["last_update"] == localInfo["last_update"]) {
        logger.info(
            this.runtimeType.toString(), "Local template is up-to-date.");
        return 0;
      } else {
        logger.info(this.runtimeType.toString(), "Local template is outdated.");
        return 1;
      }
    } else {
      logger.info(this.runtimeType.toString(),
          "Local template does not exist on the server.");
      return 2;
    }
  }

  /// Process the template and format template inventory.
  Future<Map<String, dynamic>> processTemplate() async {
    // Get the template from template.json
    var template = config.getTemplate();
    logger.info(this.runtimeType.toString(), "Processing template...");
    var value = await getInventoryResult(template, template["os"]);
    var templateInventory;
    // If the value isn't empty, it creates an object with data
    // If not, return an error
    if (value.isNotEmpty) {
      templateInventory = {
        "values": value,
        "return": "true",
      };
      logger.info(
          this.runtimeType.toString(), "Template processed successfully.");
    } else {
      templateInventory = {
        "return": "false",
      };
      logger.error(this.runtimeType.toString(),
          "Failed to process template. Template is empty.");
    }
    return templateInventory;
  }

  /// Get all informations present in the local [template]
  /// with a [os] verification and format it in json.
  Future<Map<String, dynamic>> getInventoryResult(
      Map<String, dynamic> template, String os) async {
    var format;

    // Check the os platform
    if (os == "LIN") {
      format = linuxFormat;
    } else if (template["os"] == "WIN" && Platform.isWindows) {
      format = windowsFormat;
    } else if (template["os"] == "MAC" && Platform.isMacOS) {
      format = macOSFormat;
    } else {
      logger.error(this.runtimeType.toString(), "Unsupported OS detected.");
    }

    Map<String, dynamic> inventoryResult = new Map();

    List<dynamic> sections = template['sections'];

    for (var section in sections) {
      Map<String, dynamic> result = await getResult(os, template, section);
      var valueTarget;

      // Choose the retrieval format
      switch (section['retrival_output']) {
        case "TBLE":
          valueTarget = format.getByArray(section["fields"], result);
          break;
        case "JSON":
          if (os == "MAC") {
            valueTarget =
                format.getByJson(section["fields"], result, section["target"]);
          } else {
            valueTarget = format.getByJson(section["fields"], result);
          }
          break;
        case "PTXT":
          valueTarget = await format.getByPtxt(section["fields"], result);
          break;
        case "REGX":
          valueTarget = format.getByRegx(section["fields"], result);
          break;
        case "GREP":
          valueTarget = format.getByGrep(section["fields"], result);
          break;
        default:
          valueTarget = null;
          break;
      }
      inventoryResult.putIfAbsent(section['name'], () => valueTarget);
    }

    return inventoryResult;
  }

  /// Get the result
  Future<Map<String, dynamic>> getResult(String os,
      Map<String, dynamic> template, Map<String, dynamic> section) async {
    late var command;
    Map<String, dynamic> result = new Map();

    // Check the os platform
    if (os == "LIN") {
      command = this.linuxCommand;
    } else if (template["os"] == "WIN" && Platform.isWindows) {
      command = this.windowsCommand;
    } else if (template["os"] == "MAC" && Platform.isMacOS) {
      command = this.macOSCommand;
    } else {
      logger.error(this.runtimeType.toString(), "Unsupported OS detected.");
    }

    Map<String, dynamic> main = new Map<String, dynamic>();
    Map<String, dynamic> options = new Map<String, dynamic>();
    if (section['options'] != null) {
      options = section['options'];
    }

    String mainRes =
        await command.getResult(section["target"], section['retrival_method']);
    main.putIfAbsent('name', () => section['name']);
    main.putIfAbsent('type', () => section['retrival_output']);
    main.putIfAbsent('options', () => options);
    main.putIfAbsent('result', () => mainRes);
    result.putIfAbsent('main', () => main);
    List<dynamic> test = section['fields'];
    var fieldOver = test.where((element) => element["override_target"]);

    for (var field in fieldOver) {
      Map<String, dynamic> sub = new Map<String, dynamic>();
      String res = await command.getResult(
          field["new_target"], field['retrival_method']);
      sub.putIfAbsent('name', () => field['name']);
      sub.putIfAbsent('type', () => field['retrival_output']);
      sub.putIfAbsent('options', () => field['options']);
      sub.putIfAbsent('result', () => res);
      result.putIfAbsent(field['name'], () => sub);
    }

    return result;
  }

  /// Create or update the inventory and send it to the server.
  Future<void> sendRemoteBaseInventory(Map<String, dynamic> body) async {
    if (inventoryCheck) {
      String uuid = await body['uuid'];
      uuid = uuid.isEmpty ? 'none' : uuid;

      logger.info(
          this.runtimeType.toString(), "Sending base inventory to server...");
      // Try to get the existing inventory
      // If an inventory is retrieved, check its uuid
      // If an uuid exists, update the current inventory or create one if not
      // If not dislay an error message and if there is an error, return query error

      // API call
      var response = await httpUtils.get(
          Uri.parse(url + "/asset/bases/?uuid=$uuid"),
          httpUtils.getHeader(config));
      logger.verbose(this.runtimeType.toString(), response["message"]);

      if (response["status_code"] == 200) {
        // Check if the uuid exists
        if (response["body"].contains(uuid)) {
          // Update the inventory
          logger.info(this.runtimeType.toString(), "Updating inventory...");
          var id = jsonDecode(response["body"])[0]['id'];
          // API call
          var responsePut = await httpUtils.put(
              Uri.parse(url + "/asset/bases/$id/"),
              httpUtils.getHeader(config),
              jsonEncode(body));
          logger.verbose(this.runtimeType.toString(), responsePut["message"]);

          if (responsePut["status_code"] == 200) {
            logger.info(
                this.runtimeType.toString(), "Inventory updated successfully.");
            logger.serverLogger(assetID, 2, "Inventory updated successfully.");
          } else {
            logger.error(
                this.runtimeType.toString(), "Inventory update failed.");
            logger.serverLogger(assetID, 5, "Inventory update failed.");
          }
        } else {
          logger.error(this.runtimeType.toString(),
              "UUID could not be retrieved from base inventory.");
          logger.serverLogger(
              assetID, 5, "UUID could not be retrieved from base inventory.");
        }
      } else {
        logger.error(this.runtimeType.toString(),
            "Failed to get inventory from server.");
        logger.serverLogger(assetID, 5, "Failed to get inventory from server.");
      }
    } else {
      // Create the inventory
      logger.info(this.runtimeType.toString(), "Creating new inventory...");
      // API call
      var responsePost = await httpUtils.post(Uri.parse(url + "/asset/bases/"),
          httpUtils.getHeader(config), jsonEncode(body));
      logger.verbose(this.runtimeType.toString(), responsePost["message"]);
      if (responsePost["status_code"] == 200) {
        logger.info(
            this.runtimeType.toString(), "Inventory created successfully.");
        logger.serverLogger(assetID, 1, "Inventory created successfully.");
      } else {
        logger.error(this.runtimeType.toString(), "Inventory creation failed.");
        logger.serverLogger(assetID, 5, "Inventory creation failed.");
      }
    }
  }

  /// Update the remote inventory to add template inventory
  Future<void> sendRemoteTemplateInventory(Map<String, dynamic> body) async {
    if (await getRemoteTemplate(body)) {
      var templateInventory = await processTemplate();
      logger.info(this.runtimeType.toString(),
          "Sending template inventory to server...");
      if (templateInventory["return"] != false) {
        logger.info(
            this.runtimeType.toString(), "Retrieving remote base inventory...");
        String uuid = await body['uuid'];
        uuid = uuid.isEmpty ? 'none' : uuid;

        // API call
        var response = await httpUtils.get(
            Uri.parse(url + "/asset/bases/?uuid=$uuid"),
            httpUtils.getHeader(config));
        logger.verbose(this.runtimeType.toString(), response["message"]);
        if (response["status_code"] == 200) {
          logger.info(
              this.runtimeType.toString(), "Remote base inventory found.");
          // If there is a uuid in the inventory, update the current inventory
          // Else, return an error
          if (response["body"].contains(uuid)) {
            logger.info(
                this.runtimeType.toString(), "Updating base inventory...");
            var content = jsonDecode(response["body"])[0];
            var encoder = new JsonEncoder.withIndent("\t");
            content["template_inventory"] = templateInventory["values"];
            var updatedInventory = new Map();
            if (config.getCoreConfig("agent", "inventory_checksum")) {
              late var sectionBase64, sectionBytes, sectionJson;
              sectionJson = new Map();
              content["template_inventory"].keys.forEach((element) {
                sectionBytes = utf8
                    .encode(content["template_inventory"][element].toString());
                sectionBase64 = base64.encode(sectionBytes);
                sectionJson[element] = sectionBase64;
              });
              if (!inventoryBase64.existsSync()) {
                logger.error(this.runtimeType.toString(),
                    "Can't find base64 file, creating one...");
                inventoryBase64.createSync(recursive: true);
                filesUtils.writeFile(inventoryBase64, "{}");
              }
              logger.info(this.runtimeType.toString(), "Base64 file found.");
              var fileBase64 = jsonDecode(inventoryBase64.readAsStringSync());
              sectionJson.keys.forEach((newKey) {
                fileBase64.keys.forEach((oldKey) {
                  if (newKey == oldKey) {
                    if (sectionJson[newKey] == fileBase64[oldKey]) {
                      logger.verbose(
                          this.runtimeType.toString(),
                          sprintf(
                              "%s section has not changed since last inventory.",
                              [newKey.toString()]));
                    } else {
                      logger.verbose(
                          this.runtimeType.toString(),
                          sprintf("%s section will be updated.",
                              [newKey.toString()]));
                      updatedInventory[newKey] =
                          content["template_inventory"][newKey];
                    }
                  }
                });
                if (!fileBase64.containsKey(newKey)) {
                  logger.verbose(
                      this.runtimeType.toString(),
                      sprintf("%s section added to the inventory.",
                          [newKey.toString()]));
                  updatedInventory[newKey] =
                      content["template_inventory"][newKey];
                }
              });
              filesUtils.writeFile(
                  inventoryBase64, encoder.convert(sectionJson));
            }
            var inventoryExist = await httpUtils.get(
                Uri.parse(url + "/asset/sections/?base=$assetID"),
                httpUtils.getHeader(config));
            if (inventoryExist["status_code"] == 200) {
              if (config.getCoreConfig("agent", "inventory_checksum")) {
                content["template_inventory"] = updatedInventory;
              }
              var responsePatch = await httpUtils.patch(
                  Uri.parse("$url/asset/collection/"),
                  httpUtils.getHeader(config),
                  encoder.convert(content));
              logger.verbose(
                  this.runtimeType.toString(), responsePatch["message"]);
              if (responsePatch["status_code"] == 200) {
                logger.info(this.runtimeType.toString(),
                    "Template inventory updated successfully.");
                logger.serverLogger(
                    assetID, 4, "Template inventory updated successfully.");
              } else {
                logger.error(this.runtimeType.toString(),
                    "Failed to update template inventory.");
                logger.serverLogger(
                    assetID, 6, "Failed to update template inventory.");
              }
            } else {
              // API call
              var responsePut = await httpUtils.put(
                  Uri.parse(url + "/asset/collection/"),
                  httpUtils.getHeader(config),
                  encoder.convert(content));
              logger.verbose(
                  this.runtimeType.toString(), responsePut["message"]);
              if (responsePut["status_code"] == 200) {
                logger.info(this.runtimeType.toString(),
                    "Template inventory updated successfully.");
                logger.serverLogger(
                    assetID, 6, "Template inventory updated successfully.");
              } else {
                logger.error(this.runtimeType.toString(),
                    "Failed to update template inventory.");
              }
            }
          } else {
            logger.error(
                this.runtimeType.toString(), "Missing UUID in base inventory.");
            logger.serverLogger(assetID, 6, "Missing UUID in base inventory.");
          }
        } else {
          logger.error(this.runtimeType.toString(),
              "Failed to retrieve base inventory from server.");
          logger.serverLogger(
              assetID, 6, "Failed to retrieve base inventory from server.");
        }
      } else {
        logger.error(
            this.runtimeType.toString(), "Failed to process template.");
      }
    } else {
      logger.error(
          this.runtimeType.toString(), "Failed to get remote template.");
    }
  }

  /// Create a local inventory in the JSON format.
  Future<void> sendLocalBaseInventory(Map<String, dynamic> body) async {
    logger.info(this.runtimeType.toString(), "Creating base inventory file...");
    logger.info(
        this.runtimeType.toString(), "Writing base inventory locally...");
    // Create a file to save the new inventory
    await inventoryFile.create(recursive: true);
    var encoder = await JsonEncoder.withIndent("\t");
    // Write the new inventory inside
    filesUtils.writeFile(inventoryFile, encoder.convert(body));
    logger.info(this.runtimeType.toString(),
        sprintf("New base inventory created in %s", [inventoryFileName]));
  }

  /// Update the local inventory to add template inventory
  Future<void> sendLocalTemplateInventory() async {
    logger.info(this.runtimeType.toString(),
        "Adding template inventory to local inventory...");

    if (getLocalTemplate()) {
      var templateInventory = await processTemplate();

      if (templateInventory["return"] != false) {
        // Get the local inventory
        var content = jsonDecode(inventoryFile.readAsStringSync());
        var encoder = new JsonEncoder.withIndent("\t");
        content["template_inventory"] = templateInventory["values"];
        logger.verbose(this.runtimeType.toString(),
            content["template_inventory"].toString());
        // Write into inventory file
        filesUtils.writeFile(inventoryFile, encoder.convert(content));
        logger.info(this.runtimeType.toString(),
            "Template inventory added to base inventory!");
      } else {
        logger.error(
            this.runtimeType.toString(), "Failed to process template.");
      }
    } else {
      logger.error(
          this.runtimeType.toString(), "Failed to retrieve local template.");
    }
  }
}
